# Generated by Django 4.2.4 on 2023-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrption',
            new_name='description',
        ),
    ]
